validar si log/recording está vacio

diff --git a/tasks/update-cmrecording.yml b/tasks/update-cmrecording.yml
--- a/tasks/update-cmrecording.yml
+++ b/tasks/update-cmrecording.yml
@@ -173,22 +173,24 @@
       echo -e "\n>> Esperando nuevo registro...\n";
       cd /var/log/asterisk/
       # tail -f /var/log/asterisk/recording 
-      ENDLINE=$(tail -n1 $PWD/recording);
-      TIMEOUT={{ timeout }}
-      echo "$TIMEOUT: $ENDLINE";
-      while [[ $(tail -n1 $PWD/recording) == $ENDLINE && $TIMEOUT != 0 ]]; do
-        sleep 1;
-        TIMEOUT=$(( TIMEOUT - 1 ));
-        printf "$TIMEOUT, ";
-      done
-      NEWLINE=$(tail -n1 $PWD/recording)
-      if [[ $TIMEOUT != 0 ]]; then
-        echo "Ready!";
-        echo $ENDLINE | cut -d'|' -f11;
-        echo $NEWLINE | cut -d'|' -f11;
-      else
-        >&2 echo -e "\nFAILED: Timeout and is the same line.";
-      fi     
+      if [[ $(tail ./recording) ]]; then
+        ENDLINE=$(tail -n1 $PWD/recording);
+        TIMEOUT={{ timeout }}
+        echo "$TIMEOUT: $ENDLINE";
+        while [[ $(tail -n1 $PWD/recording) == $ENDLINE && $TIMEOUT != 0 ]]; do
+          sleep 1;
+          TIMEOUT=$(( TIMEOUT - 1 ));
+          printf "$TIMEOUT, ";
+        done
+        NEWLINE=$(tail -n1 $PWD/recording)
+        if [[ $TIMEOUT != 0 ]]; then
+          echo "Ready!";
+          echo $ENDLINE | cut -d'|' -f11;
+          echo $NEWLINE | cut -d'|' -f11;
+        else
+          >&2 echo -e "\nFAILED: Timeout and is the same line.";
+        fi
+      fi
     chdir: /var/log/asterisk/
   register: recording_log
   vars: 
